# https://developers.cloudflare.com/workers/wrangler/cli-wrangler/configuration/

name = "githubissues-dev"
type = "webpack"

account_id = "f8ffb577efdf82b0303f86d7b4ca94a5"
workers_dev = true

compatibility_date = "2022-09-07"

[vars]
ENVIRONMENT = "development"
OWNER = "csssbot"
REPO = "testing"
BASE_BRANCH = "main"
USERS = "AnimeAllstar"
TEAMS = ""
LABELS = "test,octokit"
ORIGIN = "*"

[env.production]
name = "githubissues"

[env.production.vars]
ENVIRONMENT = "production"
OWNER = "ubccsss"
REPO = "ubccsss.org"
BASE_BRANCH = "master"
USERS = ""
TEAMS = "website"
LABELS = "course review"
ORIGIN = "https://ubccsss.org"
